app_abbreviations_api:
    type: rest
    prefix: /admin/api
    resource: Manuxi\SuluAbbreviationsBundle\Controller\Admin\AbbreviationsController
    name_prefix: sulu_abbreviations.
    options:
        expose: true
sulu_abbreviations_settings_api:
    type: rest
    prefix: /admin/api
    resource: Manuxi\SuluAbbreviationsBundle\Controller\Admin\SettingsController
    name_prefix: sulu_abbreviations.
    options:
        expose: true